name: Cypress tests
on:
  push:
    branches:
      - '*'
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: npm run start:e2e
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cypress run on Firefox
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: npm run start:e2e
          browser: firefox
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}